// RANGE - Returns a list of numbers in a specified range.
// The list is generated by specifying a starting point, an ending point, and an optional step value.
// The syntax for the RANGE function is as follows:
// RANGE(start, end, step)

// Example 1: Generate a list of numbers from 0 to 9
RETURN RANGE(0, 9) AS numbers

// Example 2: Generate a list of numbers from 0 to 6 with a step of -1 -> This will return an empty list since the step is negative and the start is less than the end
RETURN RANGE(0, 6, -1) AS numbers

// RANGE - Get value at index
RETURN RANGE(0, 9)[3] AS numberAtIndex3
RETURN RANGE(0, 9)[-1] AS lastNumber

// RANGE - Get a sublist, [start,stop(stop is excluded)]
RETURN RANGE(0, 9)[2..5] AS sublist
RETURN RANGE(0, 9)[..5] AS sublistFromStart
RETURN RANGE(0, 9)[5..] AS sublistToEnd
RETURN RANGE(0, 9)[0..-4] AS sublistToNegativeIndex
RETURN RANGE(0, 9)[-4..] AS sublistFromNegativeIndex
RETURN RANGE(0, 9)[..-2] AS sublistToNegativeIndex2
RETURN RANGE(0, 9)[-4..-1] AS sublistNegativeIndexToNegativeIndex

// RANGE - Out of bounds access returns null
RETURN RANGE(0, 9)[10] AS outOfBounds
RETURN RANGE(0, 9)[-11] AS outOfBoundsNegative
RETURN RANGE(0, 9)[2..15] AS outOfBoundsSublist
RETURN RANGE(0, 9)[-15..2] AS outOfBoundsSublist

// RANGE - Size of the list
RETURN SIZE(RANGE(0, 9)) AS sizeOfRange
WITH RANGE(0, 9) AS numbers
RETURN SIZE(numbers) AS sizeOfRangeFromVariable
