// UNION CLAUSE - COMBINING RESULTS OF MULTIPLE MATCHES - UNION ALL TO INCLUDE DUPLICATES
MATCH (n:Movie)
RETURN n.title AS Title
UNION // ALL
MATCH (n:Person)
RETURN n.name AS Title
UNION
MATCH (n:Movie)
RETURN n.title AS Title
